[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps"

[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

[build.processing.html]
  pretty_urls = true

[build.processing.images]
  compress = true

# Environment variables needed
[context.production.environment]
  VITE_FIREBASE_API_KEY = "AIzaSyDkcZtgKHKwxyFry2RpIslEoAnpWuUWrzM"
  VITE_FIREBASE_AUTH_DOMAIN = "ai-persona-mentor.firebaseapp.com"
  VITE_FIREBASE_PROJECT_ID = "ai-persona-mentor"
  VITE_FIREBASE_STORAGE_BUCKET = "ai-persona-mentor.firebasestorage.app"
  VITE_FIREBASE_MESSAGING_SENDER_ID = "617160220072"
  VITE_FIREBASE_APP_ID = "1:617160220072:web:b08b1649898692f4fb919d"
  VITE_FIREBASE_MEASUREMENT_ID = "G-GHFJMXHSYD" 